import { ExecutiveBriefResult } from "@/types";

export function generateExecutiveBriefMarkdown(brief: ExecutiveBriefResult): string {
  const isJa = brief.language === "ja";

  const hTitle = !isJa
    ? "# KIZUNA AI — INDIA MARKET ENTRY BRIEF"
    : "# KIZUNA AI — インド市場参入戦略エグゼクティブ・ブリーフ";
  const hCompany = !isJa ? "Company" : "企業名";
  const hProduct = !isJa ? "Product" : "製品名";
  const hTargetMarket = !isJa ? "Target Market" : "ターゲット市場";
  const hDate = !isJa ? "Generated Date" : "生成日時";
  const hConfidence = !isJa ? "AI Confidence" : "AI分析信頼度";

  const hExec = !isJa ? "## 1. EXECUTIVE SUMMARY" : "## 1. エグゼクティブ・サマリー（要約）";
  const hInd = !isJa ? "## 2. KEY DECISION-SUPPORT INDICATORS" : "## 2. 意思決定支援指標（KIZUNAスコア）";
  const hMkt = !isJa ? "## 3. MARKET OPPORTUNITY" : "## 3. 市場機会および需要動向";
  const hComp = !isJa ? "## 4. COMPETITIVE POSITION & GAP ANALYSIS" : "## 4. 競合状況およびポジショニング";
  const hPart = !isJa ? "## 5. PARTNER STRATEGY & ECOSYSTEM" : "## 5. パートナー戦略およびエコシステム";
  const hRisk = !isJa ? "## 6. RISK & ADVERSARIAL RED TEAM ASSESSMENT" : "## 6. リスク評価およびレッドチーム検証結果";
  const hEntry = !isJa ? "## 7. ENTRY STRATEGY" : "## 7. 市場参入基本戦略";
  const hPlan = !isJa ? "## 8. 90-DAY EXECUTION ROADMAP" : "## 8. 90日間実行ロードマップ";
  const hActions = !isJa ? "## 9. NEXT 3 PRIORITY ACTIONS" : "## 9. 最優先アクション（直近3件）";
  const hGates = !isJa ? "## 10. DECISION GATES" : "## 10. 意思決定ゲート（評価基準）";
  const hAssump = !isJa ? "## 11. KEY OPERATIONAL ASSUMPTIONS" : "## 11. 前提条件（アサンプション）";
  const hEvi = !isJa ? "## 12. EVIDENCE & AUDIT TRAIL" : "## 12. エビデンスおよび監査証跡";

  let md = `${hTitle}\n\n`;
  md += `**${hCompany}:** ${brief.company}  \n`;
  md += `**${hProduct}:** ${brief.product}  \n`;
  md += `**${hTargetMarket}:** ${brief.target_market}  \n`;
  md += `**${hDate}:** ${brief.generated_at}  \n`;
  md += `**${hConfidence}:** ${(brief.confidence * 100).toFixed(0)}%  \n\n`;

  md += `---\n\n`;
  md += `${hExec}\n\n${brief.executive_summary}\n\n`;

  md += `${hInd}\n\n`;
  md += `| ${!isJa ? "Indicator" : "指標"} | ${!isJa ? "Score / Level" : "スコア / レベル"} | ${!isJa ? "Assessment" : "評価"} |\n`;
  md += `|---|---|---|\n`;
  md += `| ${!isJa ? "Market Fit Score" : "市場適合性スコア"} | ${brief.indicators.market_fit_score}/100 | ${!isJa ? "High Bilateral Fit" : "高適合"} |\n`;
  md += `| ${!isJa ? "Partner Match Fit" : "パートナー適合度"} | ${brief.indicators.partner_fit_score}/100 | ${!isJa ? "Strong Tier-1 Network" : "強固なSI網"} |\n`;
  md += `| ${!isJa ? "Launch Risk Level" : "ローンチリスク評価"} | ${brief.indicators.launch_risk_level} | ${!isJa ? "Mitigated by 90-Day Plan" : "計画内で低減可能"} |\n`;
  md += `| ${!isJa ? "Composite Confidence" : "総合分析信頼度"} | ${(brief.indicators.confidence_score * 100).toFixed(0)}% | ${!isJa ? "Multi-Agent Grounded" : "多層検証済"} |\n\n`;

  md += `${hMkt}\n\n${brief.market_opportunity}\n\n`;
  md += `${hComp}\n\n${brief.competitive_position}\n\n`;
  md += `${hPart}\n\n${brief.partner_strategy}\n\n`;
  md += `${hRisk}\n\n${brief.risk_summary}\n\n`;
  md += `${hEntry}\n\n${brief.entry_strategy}\n\n`;

  const planText = brief.plan_90_day || brief["90_day_plan"] || "N/A";
  md += `${hPlan}\n\n${planText}\n\n`;

  md += `${hActions}\n\n`;
  brief.next_actions.forEach((a, i) => {
    md += `### ${i + 1}. ${a.action}\n`;
    md += `- **${!isJa ? "Strategic Urgency" : "実施理由"}:** ${a.why_now}\n`;
    md += `- **${!isJa ? "Expected Outcome" : "期待される成果"}:** ${a.expected_outcome}\n`;
    md += `- **${!isJa ? "Dependency" : "依存関係"}:** ${a.dependency}\n\n`;
  });

  md += `${hGates}\n\n`;
  brief.decision_gates.forEach((g, i) => {
    md += `### ${g.gate} [${g.status}]\n`;
    md += `- **${!isJa ? "Core Question" : "検証課題"}:** ${g.question}\n`;
    md += `- **${!isJa ? "Decision Owner" : "承認責任者"}:** ${g.decision_owner}\n`;
    md += `- **${!isJa ? "Required Evidence" : "必要エビデンス"}:** ${g.required_evidence.join(", ")}\n\n`;
  });

  md += `${hAssump}\n\n`;
  brief.key_assumptions.forEach((asm) => {
    md += `- ${asm}\n`;
  });
  md += `\n`;

  md += `${hEvi}\n\n`;
  md += `| ${!isJa ? "Category" : "分類"} | ${!isJa ? "Statement" : "ファクト / 推論内容"} | ${!isJa ? "Source Stage" : "算出元"} |\n`;
  md += `|---|---|---|\n`;
  brief.evidence.forEach((e) => {
    md += `| ${e.category} | ${e.statement} | ${e.source_stage} |\n`;
  });
  md += `\n`;

  md += `---\n*Generated by KIZUNA AI Bilateral Intelligence Engine*\n`;
  return md;
}

export function downloadMarkdownBrief(brief: ExecutiveBriefResult) {
  const md = generateExecutiveBriefMarkdown(brief);
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `KIZUNA_AI_Executive_Brief_${brief.language.toUpperCase()}_CR500.md`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function exportPrintablePdfView(brief: ExecutiveBriefResult) {
  const isJa = brief.language === "ja";
  const title = !isJa
    ? "KIZUNA AI — Executive Brief (CR-500)"
    : "KIZUNA AI — エグゼクティブ・ブリーフ (CR-500)";

  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    alert("Please allow popups to export the boardroom PDF.");
    return;
  }

  const html = `<!DOCTYPE html>
<html lang="${brief.language}">
<head>
  <meta charset="utf-8">
  <title>${title}</title>
  <style>
    @page { size: A4; margin: 20mm; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
      color: #0f172a;
      line-height: 1.5;
      font-size: 11pt;
      padding: 24px;
      max-width: 800px;
      margin: 0 auto;
    }
    .header-bar {
      border-bottom: 2px solid #3b82f6;
      padding-bottom: 12px;
      margin-bottom: 20px;
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
    }
    .brand { font-size: 18pt; font-weight: bold; color: #1e293b; }
    .badge {
      display: inline-block;
      padding: 4px 10px;
      border-radius: 4px;
      font-size: 9pt;
      font-weight: 600;
      background: #eff6ff;
      color: #1d4ed8;
      border: 1px solid #bfdbfe;
    }
    h1 { font-size: 16pt; margin: 0 0 6px 0; color: #0f172a; }
    h2 { font-size: 12pt; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; margin-top: 20px; color: #1e293b; text-transform: uppercase; letter-spacing: 0.5px; }
    h3 { font-size: 10.5pt; margin: 12px 0 4px 0; color: #334155; }
    .meta-grid {
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 8px;
      background: #f8fafc;
      padding: 12px;
      border-radius: 6px;
      border: 1px solid #e2e8f0;
      margin-bottom: 16px;
      font-size: 9.5pt;
    }
    .indicators-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 8px;
      margin: 12px 0;
    }
    .indicator-card {
      background: #f1f5f9;
      padding: 10px;
      border-radius: 6px;
      text-align: center;
      border: 1px solid #cbd5e1;
    }
    .indicator-val { font-size: 14pt; font-weight: bold; color: #2563eb; }
    .indicator-lbl { font-size: 8pt; text-transform: uppercase; color: #64748b; margin-top: 2px; }
    table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 9pt; }
    th, td { border: 1px solid #cbd5e1; padding: 6px 8px; text-align: left; }
    th { background: #f8fafc; font-weight: 600; }
    .pill { display: inline-block; padding: 2px 6px; border-radius: 3px; font-size: 7.5pt; font-weight: 600; }
    .pill-source { background: #dbeafe; color: #1e40af; }
    .pill-ai { background: #fef3c7; color: #92400e; }
    .pill-assump { background: #f3e8ff; color: #6b21a8; }
    .no-print-btn {
      position: fixed;
      bottom: 20px;
      right: 20px;
      padding: 10px 20px;
      background: #2563eb;
      color: white;
      border: none;
      border-radius: 6px;
      font-weight: 600;
      cursor: pointer;
      box-shadow: 0 4px 12px rgba(37,99,235,0.3);
    }
    @media print {
      .no-print-btn { display: none; }
      body { padding: 0; }
    }
  </style>
</head>
<body>
  <div class="header-bar">
    <div>
      <div class="brand">KIZUNA AI 絆</div>
      <div style="font-size: 9pt; color: #64748b;">Autonomous Bilateral Market Intelligence Platform (Japan ⇄ India)</div>
    </div>
    <span class="badge">${brief.language.toUpperCase()} BRIEF</span>
  </div>

  <h1>${brief.title}</h1>

  <div class="meta-grid">
    <div><strong>${!isJa ? "Target Enterprise" : "日本側進出企業"}:</strong> ${brief.company}</div>
    <div><strong>${!isJa ? "Solution / Product" : "対象製品"}:</strong> ${brief.product}</div>
    <div><strong>${!isJa ? "Market Corridor" : "対象市場"}:</strong> ${brief.target_market}</div>
    <div><strong>${!isJa ? "Confidence Score" : "総合分析信頼度"}:</strong> ${(brief.confidence * 100).toFixed(0)}%</div>
  </div>

  <h2>${!isJa ? "1. Key Decision Indicators" : "1. 意思決定指標"}</h2>
  <div class="indicators-grid">
    <div class="indicator-card">
      <div class="indicator-val">${brief.indicators.market_fit_score}/100</div>
      <div class="indicator-lbl">${!isJa ? "Market Fit" : "市場適合性"}</div>
    </div>
    <div class="indicator-card">
      <div class="indicator-val">${brief.indicators.partner_fit_score}/100</div>
      <div class="indicator-lbl">${!isJa ? "Partner Fit" : "パートナー適合度"}</div>
    </div>
    <div class="indicator-card">
      <div class="indicator-val" style="font-size: 11pt; padding-top: 4px;">${brief.indicators.launch_risk_level}</div>
      <div class="indicator-lbl">${!isJa ? "Launch Risk" : "リスク評価"}</div>
    </div>
    <div class="indicator-card">
      <div class="indicator-val">${(brief.indicators.confidence_score * 100).toFixed(0)}%</div>
      <div class="indicator-lbl">${!isJa ? "Confidence" : "信頼度"}</div>
    </div>
  </div>

  <h2>${!isJa ? "2. Executive Summary" : "2. エグゼクティブ・サマリー"}</h2>
  <p>${brief.executive_summary}</p>

  <h2>${!isJa ? "3. Market Opportunity & Demand" : "3. 市場機会および需要動向"}</h2>
  <p style="white-space: pre-line;">${brief.market_opportunity}</p>

  <h2>${!isJa ? "4. Competitive Position & Whitespace" : "4. 競合状況およびポジショニング"}</h2>
  <p style="white-space: pre-line;">${brief.competitive_position}</p>

  <h2>${!isJa ? "5. Partner & Ecosystem Strategy" : "5. パートナー戦略"}</h2>
  <p style="white-space: pre-line;">${brief.partner_strategy}</p>

  <h2>${!isJa ? "6. Risk & Adversarial Red Team" : "6. リスク評価と検証結果"}</h2>
  <p style="white-space: pre-line;">${brief.risk_summary}</p>

  <h2>${!isJa ? "7. 90-Day Execution Roadmap" : "7. 90日間実行ロードマップ"}</h2>
  <p style="white-space: pre-line; font-family: monospace; font-size: 8.5pt; background: #f8fafc; padding: 10px; border-radius: 4px; border: 1px solid #e2e8f0;">${brief.plan_90_day || brief["90_day_plan"] || "N/A"}</p>

  <h2>${!isJa ? "8. Immediate Next Actions" : "8. 最優先アクション"}</h2>
  ${brief.next_actions
    .map(
      (a, i) => `
    <div style="margin-bottom: 8px;">
      <strong>${i + 1}. ${a.action}</strong>
      <div style="font-size: 8.5pt; color: #475569; margin-left: 14px;">
        • ${!isJa ? "Urgency" : "理由"}: ${a.why_now} | ${!isJa ? "Outcome" : "成果"}: ${a.expected_outcome}
      </div>
    </div>`
    )
    .join("")}

  <h2>${!isJa ? "9. Decision Gates" : "9. 意思決定ゲート"}</h2>
  ${brief.decision_gates
    .map(
      (g) => `
    <div style="margin-bottom: 8px;">
      <strong>${g.gate} [${g.status}]</strong>: ${g.question}
      <div style="font-size: 8.5pt; color: #475569; margin-left: 14px;">
        • ${!isJa ? "Owner" : "承認者"}: ${g.decision_owner} | ${!isJa ? "Evidence" : "証跡"}: ${g.required_evidence.join(", ")}
      </div>
    </div>`
    )
    .join("")}

  <h2>${!isJa ? "10. Evidence Classification" : "10. エビデンス監査証跡"}</h2>
  <table>
    <thead>
      <tr>
        <th style="width: 15%;">${!isJa ? "Tier" : "分類"}</th>
        <th>${!isJa ? "Statement" : "ファクト / 内容"}</th>
        <th style="width: 25%;">${!isJa ? "Source Stage" : "算出元"}</th>
      </tr>
    </thead>
    <tbody>
      ${brief.evidence
        .map(
          (e) => `
        <tr>
          <td><span class="pill ${e.category === "SOURCE DATA" ? "pill-source" : e.category === "AI INFERENCE" ? "pill-ai" : "pill-assump"}">${e.category}</span></td>
          <td>${e.statement}</td>
          <td>${e.source_stage}</td>
        </tr>`
        )
        .join("")}
    </tbody>
  </table>

  <div style="margin-top: 30px; padding-top: 10px; border-top: 1px solid #cbd5e1; font-size: 8pt; color: #94a3b8; text-align: center;">
    Confidential Boardroom Brief • Generated by KIZUNA AI Bilateral Intelligence Engine
  </div>

  <button class="no-print-btn" onclick="window.print()">🖨️ Print / Save as PDF</button>
</body>
</html>`;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
}
